# Generated by Django 5.0.14 on 2026-07-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.IntegerField()),
                ('seo_score', models.IntegerField()),
                ('accessibility_score', models.IntegerField()),
                ('best_practices_score', models.IntegerField()),
                ('lcp', models.FloatField(help_text='Largest Contentful Paint in seconds')),
                ('cls', models.FloatField(help_text='Cumulative Layout Shift')),
                ('inp', models.FloatField(help_text='Interaction to Next Paint in seconds')),
                ('fcp', models.FloatField(help_text='First Contentful Paint in seconds')),
                ('ttfb', models.FloatField(help_text='Time to First Byte in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('404', '404 Not Found'), ('500', '500 Server Error'), ('api_failure', 'API Failure'), ('database', 'Database Error'), ('cloudinary', 'Cloudinary Error'), ('openai', 'OpenAI Error'), ('form_submission', 'Form Submission Failure')], max_length=50)),
                ('source', models.CharField(help_text='e.g. URL pathway, view function, task name', max_length=255)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='unresolved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
