# Generated by Django 5.0.14 on 2026-07-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_performancemetric_searchquerylog_systemerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigenerationlog',
            name='action_type',
            field=models.CharField(choices=[('product_text', 'Product Content (text)'), ('product_image', 'Product Content (image analysis)'), ('blog_manual', 'Blog (manual)'), ('blog_auto', 'Blog (automated scheduler)'), ('datasheet', 'Product Datasheet PDF'), ('chat', 'Kivi Agent Chat')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('escalated', models.BooleanField(default=False, help_text='True when the assistant surfaced contact options (high purchase intent).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='analytics_c_session_0bd9c3_idx')],
            },
        ),
    ]
