# Generated by Django 5.0.14 on 2026-07-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_aigenerationlog_action_type_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='Lighthouse improvement opportunities: [{"title": "...", "detail": "..."}]'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='strategy',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', max_length=10),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='url',
            field=models.URLField(blank=True, help_text='Page that was audited'),
        ),
    ]
