from django.db import models
from django.utils.text import slugify
from django.core.validators import MinValueValidator, MaxValueValidator


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)
    description = models.TextField(blank=True)

    # SEO
    seo_title = models.CharField(max_length=60, blank=True)
    seo_description = models.CharField(max_length=160, blank=True)

    # Media
    image = models.URLField(blank=True)               # Listing card image
    featured_image = models.URLField(blank=True)      # Category landing hero
    header_image = models.URLField(blank=True)        # Wide banner image

    # Category landing page content (600+ words target for independent ranking)
    overview_content = models.TextField(
        blank=True,
        help_text="600+ word editorial content about this category. Used for SEO category landing page."
    )
    benefits = models.JSONField(
        default=list,
        help_text='[{"title": "...", "description": "...", "icon": "..."}, ...]'
    )
    industries_served = models.JSONField(
        default=list,
        help_text='["Manufacturing", "Water Treatment", ...]'
    )
    faq = models.JSONField(
        default=list,
        help_text='[{"question": "...", "answer": "..."}, ...]'
    )

    order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order', 'name']
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(models.Model):
    # ── Identity ──
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='products'
    )

    # ── Chemical Properties ──
    chemical_formula = models.CharField(max_length=100, blank=True)   # e.g. NaOH
    cas_number = models.CharField(max_length=20, blank=True)           # e.g. 1310-73-2
    un_number = models.CharField(max_length=20, blank=True)            # Hazmat UN number
    purity = models.CharField(max_length=50, blank=True)               # e.g. "99.0% min"
    molecular_weight = models.CharField(max_length=30, blank=True)     # e.g. "40.00 g/mol"
    appearance = models.CharField(max_length=150, blank=True)          # e.g. "White crystalline powder"
    grade = models.CharField(max_length=100, blank=True)               # Industrial / Food / Technical / Lab

    # ── Packaging ──
    packaging = models.JSONField(
        default=list,
        help_text='[{"size": "25kg", "type": "bag"}, {"size": "200L", "type": "drum"}]'
    )

    # ── Content ──
    short_description = models.CharField(max_length=300, blank=True)
    description = models.TextField(blank=True)
    applications = models.JSONField(default=list)     # ["Water treatment", "Soap making"]
    specifications = models.JSONField(default=dict)   # {"Purity": "99%", "Form": "Powder"}
    safety_info = models.TextField(blank=True)        # Handling, storage, hazard info

    # ── Documents (Cloudinary URLs) ──
    sds_pdf = models.URLField(blank=True, help_text="Safety Data Sheet — Cloudinary URL")
    datasheet_pdf = models.URLField(
        blank=True,
        help_text="Product Datasheet — auto-generated by Celery on save"
    )

    # ── SEO ──
    seo_title = models.CharField(max_length=60, blank=True)
    seo_description = models.CharField(max_length=160, blank=True)
    keywords = models.CharField(max_length=300, blank=True)
    schema_data = models.JSONField(
        default=dict,
        blank=True,
        help_text="Auto-populated Product JSON-LD schema. Admin can override."
    )
    alt_text = models.CharField(
        max_length=200, blank=True,
        help_text="AI-generated image alt text for accessibility"
    )

    # ── AI-Generated Content ──
    ai_generated = models.BooleanField(default=False)
    ai_title = models.CharField(max_length=200, blank=True)
    ai_summary = models.CharField(max_length=500, blank=True)
    ai_benefits = models.JSONField(default=list, blank=True)
    ai_faq = models.JSONField(
        default=list, blank=True,
        help_text='[{"question": "...", "answer": "..."}, ...]'
    )
    ai_industries = models.JSONField(default=list, blank=True)
    internal_links = models.JSONField(
        default=list, blank=True,
        help_text='[{"title": "...", "slug": "..."}] — related products/categories'
    )
    external_references = models.JSONField(
        default=list, blank=True,
        help_text='[{"title": "PubChem", "url": "...", "nofollow": false}]'
    )

    # ── Media ──
    image = models.URLField(blank=True)
    images = models.JSONField(default=list)

    # ── Status Flags ──
    is_active = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    in_stock = models.BooleanField(default=True)

    # ── Analytics ──
    view_count = models.PositiveIntegerField(default=0)
    quote_request_count = models.PositiveIntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-is_featured', '-created_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class SiteSetting(models.Model):
    """Singleton model — only one row. Read via SiteSetting.get_solo()"""

    # ── Company ──
    company_name = models.CharField(max_length=200, default='')
    tagline = models.CharField(max_length=300, default='')
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=20, blank=True)
    whatsapp = models.CharField(max_length=20, blank=True)
    whatsapp_fr = models.CharField(
        max_length=20, blank=True,
        help_text="Optional separate WhatsApp number for French-speaking markets (DRC, Rwanda, Burundi)"
    )
    address = models.TextField(blank=True)
    city = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, default='Kenya')
    opening_hours = models.CharField(max_length=200, blank=True)

    # ── Branding ──
    logo = models.URLField(blank=True)
    favicon = models.URLField(blank=True)

    # ── SEO Defaults ──
    default_seo_title = models.CharField(max_length=60, blank=True)
    default_seo_description = models.CharField(max_length=160, blank=True)
    default_keywords = models.CharField(max_length=500, blank=True)

    # ── Social ──
    linkedin_url = models.URLField(blank=True)
    facebook_url = models.URLField(blank=True)
    instagram_url = models.URLField(blank=True)
    twitter_url = models.URLField(blank=True)

    # ── Analytics (editable from admin; override env defaults) ──
    google_analytics_id = models.CharField(max_length=20, blank=True)
    google_site_verification = models.CharField(max_length=100, blank=True)

    # ── AI Blog Settings ──
    auto_publish_blogs = models.BooleanField(
        default=False,
        help_text="If True, AI-generated blogs are auto-published without admin review. Default: require approval."
    )
    blog_posts_per_week = models.IntegerField(
        default=2,
        validators=[MinValueValidator(0), MaxValueValidator(7)],
        help_text="Number of automated blog posts to generate per week (0 to disable)."
    )

    # ── Technical (stored here so they're editable, not hardcoded) ──
    revalidate_secret = models.CharField(max_length=100, blank=True)

    class Meta:
        verbose_name = 'Site Setting'

    @classmethod
    def get_solo(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

    def __str__(self):
        return self.company_name or "Site Setting"


class SavedProduct(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='saved_products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='saved_by')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        unique_together = ('user', 'product')

    def __str__(self):
        return f"{self.user.username} saved {self.product.name}"

