# Generated by Django 5.0.14 on 2026-07-01 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='article_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-populated Article JSON-LD schema'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='auto_published',
            field=models.BooleanField(default=False, help_text='True if published automatically via scheduler without admin review'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='external_references',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "WHO", "url": "...", "nofollow": false}]'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='[{"question": "...", "answer": "..."}, ...]'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_prompt',
            field=models.TextField(blank=True, help_text='AI prompt used to generate the featured image (for audit/regeneration)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "slug": "...", "type": "product|category|blog"}]'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='quality_score',
            field=models.IntegerField(default=0, help_text='0-100 score computed by AI quality audit (readability, depth, SEO)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.IntegerField(default=0, help_text='Estimated reading time in minutes (computed on save)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory'),
        ),
    ]
