# Generated by Django 5.0.14 on 2026-07-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_is_published_alter_blogpost_slug'),
        ('blog', '0002_blogcategory_blogpost_ai_generated_and_more'),
    ]

    operations = [
    ]
