# Generated by Django 5.0.14 on 2026-07-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='attachment_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='attachment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='inquiry_type',
            field=models.CharField(choices=[('quotation', 'Request Quotation'), ('product_info', 'Product Information'), ('technical_support', 'Technical Support'), ('bulk_order', 'Bulk Order'), ('partnership', 'Partnership Inquiry'), ('general', 'General Inquiry')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='product_interest',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
