version = 5.6.0
archive_dir = /etc/letsencrypt/archive/kivichemicals.com
cert = /etc/letsencrypt/live/kivichemicals.com/cert.pem
privkey = /etc/letsencrypt/live/kivichemicals.com/privkey.pem
chain = /etc/letsencrypt/live/kivichemicals.com/chain.pem
fullchain = /etc/letsencrypt/live/kivichemicals.com/fullchain.pem
[renewalparams]
account = e3190ca792a2ef7c6a85c09c828eca32
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
