# Generated by Django 5.0.14 on 2026-07-01 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='benefits',
            field=models.JSONField(default=list, help_text='[{"title": "...", "description": "...", "icon": "..."}, ...]'),
        ),
        migrations.AddField(
            model_name='category',
            name='faq',
            field=models.JSONField(default=list, help_text='[{"question": "...", "answer": "..."}, ...]'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='header_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='industries_served',
            field=models.JSONField(default=list, help_text='["Manufacturing", "Water Treatment", ...]'),
        ),
        migrations.AddField(
            model_name='category',
            name='overview_content',
            field=models.TextField(blank=True, help_text='600+ word editorial content about this category. Used for SEO category landing page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_faq',
            field=models.JSONField(blank=True, default=list, help_text='[{"question": "...", "answer": "..."}, ...]'),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_industries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, help_text='AI-generated image alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='appearance',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet_pdf',
            field=models.URLField(blank=True, help_text='Product Datasheet — auto-generated by Celery on save'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_references',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "PubChem", "url": "...", "nofollow": false}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "slug": "..."}] — related products/categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='molecular_weight',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.JSONField(default=list, help_text='[{"size": "25kg", "type": "bag"}, {"size": "200L", "type": "drum"}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='purity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='quote_request_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='schema_data',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-populated Product JSON-LD schema. Admin can override.'),
        ),
        migrations.AddField(
            model_name='product',
            name='sds_pdf',
            field=models.URLField(blank=True, help_text='Safety Data Sheet — Cloudinary URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='auto_publish_blogs',
            field=models.BooleanField(default=False, help_text='If True, AI-generated blogs are auto-published without admin review. Default: require approval.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='blog_posts_per_week',
            field=models.IntegerField(default=2, help_text='Number of automated blog posts to generate per week (0 to disable).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='revalidate_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_fr',
            field=models.CharField(blank=True, help_text='Optional separate WhatsApp number for French-speaking markets (DRC, Rwanda, Burundi)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='chemical_formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
