# Generated by Django 5.0.14 on 2026-07-03 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_savedproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='in_stock', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='StockMovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('reserve', 'Stock Reserve'), ('release', 'Stock Release')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_formula', models.CharField(blank=True, max_length=100)),
                ('product_description', models.TextField(blank=True)),
                ('technical_specifications', models.JSONField(blank=True, default=dict)),
                ('physical_properties', models.JSONField(blank=True, default=dict)),
                ('chemical_properties', models.JSONField(blank=True, default=dict)),
                ('industrial_applications', models.JSONField(blank=True, default=list)),
                ('purity', models.CharField(blank=True, max_length=50)),
                ('appearance', models.CharField(blank=True, max_length=150)),
                ('solubility', models.CharField(blank=True, max_length=150)),
                ('density', models.CharField(blank=True, max_length=50)),
                ('ph', models.CharField(blank=True, max_length=20)),
                ('packaging', models.TextField(blank=True)),
                ('storage_conditions', models.TextField(blank=True)),
                ('shelf_life', models.CharField(blank=True, max_length=100)),
                ('safety_notes', models.TextField(blank=True)),
                ('handling_recommendations', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tds', to='products.product')),
            ],
        ),
    ]
