# Generated by Django 5.0.14 on 2026-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_is_featured_product_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applications_detailed',
            field=models.JSONField(blank=True, default=list, help_text='Each use case explained individually: [{"title": "Water Treatment", "description": "..."}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_content',
            field=models.TextField(blank=True, help_text='Benefits and advantages in flowing paragraphs (cost, performance, operational, industry).'),
        ),
        migrations.AddField(
            model_name='product',
            name='introduction',
            field=models.TextField(blank=True, help_text="Product introduction (150-300 words): what it is, why it's used, industries, commercial importance."),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_info',
            field=models.TextField(blank=True, help_text='Prose explanation of packaging options, bulk supply, and commercial formats.'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_handling',
            field=models.TextField(blank=True, help_text='Detailed storage conditions and handling guidance.'),
        ),
    ]
