# Generated by Django 5.0.14 on 2026-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_applications_detailed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='un_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
