# Generated by Django 5.0.14 on 2026-07-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_slugredirect_and_widen_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='grades_available',
            field=models.JSONField(blank=True, default=list, help_text='Industry-standard grades this chemical genuinely comes in: [{"grade": "Food Grade", "note": "..."}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='hazard_classification',
            field=models.CharField(blank=True, help_text="Concise GHS classification summary, e.g. 'GHS Category 1B – Corrosive (H314); Signal word: Danger'", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='regulatory_compliance',
            field=models.JSONField(blank=True, default=list, help_text='["Meets ISO 3696 Grade 2", "REACH registered"]'),
        ),
    ]
