# Generated by Django 5.0.14 on 2026-07-10 00:00

from django.db import migrations, models


def set_existing_products_featured(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(is_featured=False).update(is_featured=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_brand_product_grades_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_existing_products_featured, noop_reverse),
    ]
